---
name: Open Pull Request

on: [pull_request]

jobs:
  run_checks:
    name: Run Linter
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2

      - uses: hadolint/hadolint-action@v1.5.0
        with:
          dockerfile: Dockerfile

  build_amd64:
    name: Build code on AMD64 Architecture
    runs-on: ubuntu-latest
    needs: [run_checks]
    steps:
      - uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
