---
name: Open Pull Request

on: [pull_request]

jobs:
  run_checks:
    name: Run Linter
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2

      - name: lint
        uses: luke142367/Docker-Lint-Action@v1.0.0
        with:
          target: Dockerfile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_amd64:
    name: Build code on AMD64 Architecture
    runs-on: ubuntu-latest
    needs: [run_checks]
    steps:
      - uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
